# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e772d38be236703e9a078d100c1f07ddc9a219c0344a412d7a1519348eabfb6cecc5c0785ba5f5bf2094aae8ae8e0bc892e919c9bf9bf485e17407901630115c

test:
  secret_key_base: be420b074ae203a4a3b198959b75366bd98ef5187ca9918383948c4542bd322df0560ad66f28f8619f55a9125fccddfa35716abecc868d996329998a03578ec8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
